### ISSUE TITLE
Correct layout for notched android devices

### ISSUE THREAD

**Issue by ddovod** [brackeen/glfm#21]
Hi. Thank you very much for such an awesome library! It saved a lot of my time.
Could you please consider adding something like this to the `_glfmSetFullScreen` in the android implementation?
```cpp
    if (SDK_INT >= 28) {
        static const int WindowManager_LayoutParams_LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES = 0x00000001;
        jobject window = _glfmCallJavaMethod(jni, app->activity->clazz, "getWindow", "()Landroid/view/Window;", Object);
        jobject attributes = _glfmCallJavaMethod(jni, window, "getAttributes", "()Landroid/view/WindowManager$LayoutParams;", Object);
        jclass clazz = (*jni)->GetObjectClass(jni, attributes);
        jfieldID mi = (*jni)->GetFieldID(jni, clazz, "layoutInDisplayCutoutMode", "I");

        (*jni)->SetIntField(jni, attributes, mi, WindowManager_LayoutParams_LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES);
        (*jni)->DeleteLocalRef(jni, clazz);
        (*jni)->DeleteLocalRef(jni, attributes);
        (*jni)->DeleteLocalRef(jni, window);
    }
```
I use this piece of code in my copy of the library to deal with notched devices, works fine.
Also this helps to deal with insets (`glfmGetDisplayChromeInsets`):
```cpp
    if (SDK_INT >= 28) {
        JNIEnv *jni = platformData->jniEnv;
        jobject decorView = _glfmGetDecorView(platformData->app);
        jobject insets = _glfmCallJavaMethod(jni, decorView, "getRootWindowInsets", "()Landroid/view/WindowInsets;", Object);
        jobject cutouts = _glfmCallJavaMethod(jni, insets, "getDisplayCutout", "()Landroid/view/DisplayCutout;", Object);
        *top = _glfmCallJavaMethod(jni, cutouts, "getSafeInsetTop", "()I", Int);
        *right = _glfmCallJavaMethod(jni, cutouts, "getSafeInsetRight", "()I", Int);
        *bottom = _glfmCallJavaMethod(jni, cutouts, "getSafeInsetBottom", "()I", Int);
        *left = _glfmCallJavaMethod(jni, cutouts, "getSafeInsetLeft", "()I", Int);
    }
```
For more info please see
https://developer.android.com/guide/topics/display-cutout
https://developer.android.com/reference/android/view/WindowManager.LayoutParams#LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES

*Edit: added second piece of code for insets

**Comment by brackeen** [comment]
Thanks for the issue, @ddovod. This is added in https://github.com/brackeen/glfm/commit/379d085db611e18beab4f4861ec90a535730080f

A couple things:
* When backgrounding and then foregrounding, there was a crash when setting `layoutInDisplayCutoutMode` in `_glfmSetFullScreen`. To avoid this, `layoutInDisplayCutoutMode` is set once on startup.
* Safe insets are only used for fullscreen mode, otherwise system window insets are used.

I think this covers all the cases, but feel free to create another issue if you see any problems.

**Comment by Anuken** [comment]
This change makes handling notched layout significantly less convenient for certain apps, since it forces the application itself to handle notches and safe insets. I would like to be able to specify the type of notch behavior, or at least disable this code and use the default (black bars around notch). 

@brackeen Would you accept a PR to make this behavior configurable? What would be the best way to achieve this - through a new surface configuration option, or a `#define NOTCH_NO_SHORT_EDGES`.

**Comment by brackeen** [comment]
@Anuken I'm not sure "black bars around notch" would work on iOS, because the App Store requires notch support. It's probably better to handle notches on the app level, but having adding  Android-only switch would be fine.

**Comment by Anuken** [comment]
> the App Store requires notch support

Strange, I had an app on iOS with no notch support for more than a year, and the review system didn't have any issue with it. In fact, I even had screenshots with black bars visible on the store.

> It's probably better to handle notches on the app level

That's fair, but the app I'm using GLFM for currently doesn't target iOS, so black bars on Android are acceptable.
